@startuml

class transport
{
  {field} time_request: время, прошедшее с последнего запроса о координатах
  {field} coordinates: хранит координаты транспорта
  {field} speed: хранит скорость транспорта
  {field} Arrival_time: хранит ожидаемое время прибытия транспорта
{method} + get_coordinates(): получает координаты транспорта из карт и кладёт их в поле coordinates через определённый промежуток времени
{method} + get_speed(): получает скорость транспорта из карт и кладёт в поле speed через определённый промежуток времени
{method} + get_Arrival_time(): получает ожидаемое время прибытия транспорта с карт и кладёт в поле  через определённый промежуток времени.
}
transport .> api

class interface
{
{method} + work_notifications(): принимает и выводит push уведомления
{method} + work_user_input(): принимает и отправляет информацию пользователя.
{method} + window(): распологает информацию при открытии преложения на экране.
}
transport <. interface

class user
{
  {field} user_name: имя пользователя
  {field} gmail_or_fon: электронная почта или телефон пользователя.
  {field} user_coordinates: хранит координаты пользователя
{method} + get_coordinates(): местоположение пользователя.
}
user <. interface
user <. api

class api
{
{method} + work_requests(): отправляет запросы к яндекс картам и принимает информацию от них
}

@enduml