@startuml

class transport
{
  {field} time_request: время, прошедшее с последнего запроса о координатах
{method} + coordinates(): местоположение транспорта
{method} + speed(): скорость транспорта
{method} + Arrival_time(): ожидаемое время прибытия транспорта
}
transport .> api

class interface
{
{method} + notifications(): принимает и выводит push уведомления
{method} + editor(): принимает и отправляет информацию пользователя.
{method} + window(): распологает информацию при открытии преложения на экране.
}
transport <. interface

class user
{
  {field} user_name: имя пользователя
  {field} gmail_or_fon: электронная почта или телефон пользователя.
{method} + coordinates(): местоположение пользователя.
}
user <. interface
user <. api

class api
{
{method} + request(): отправляет запросы к внешнему источнику и принимает информацию из этого источника
}

@enduml