@startuml

actor user
(заходит в преложение, вводит номер транспорта, говорит преслать уведомление когда он подойдёт) as (ac1)
(смотрит ожидаемое время прибытия) as (ac2)
user -> ac1
user -> ac2

@enduml