@startuml

actor user
(заходит в преложение) as (ac1)
(вводит номер транспорта) as (ac2)
(говорит преслать уведомление когда он подойдёт) as (ac3)
(смотрит ожидаемое время прибытия) as (ac4)
user -> ac1
ac1 -> ac2
ac2 -> ac3
ac3 -> ac4

@enduml